---
title: "Chapter 1 self project"
author: "Harrison Linder"
date: "`r Sys.Date()`"
output: html_document
---
#Objective
In the first chapter of Data Science For Public Policy, I learned how to work with spatial census data in R. Through the excercises, we queried acs census tract level demographic and economic data from philidelphia and paired it with philidelphia's public transit system spatial data to see if people were willing to pay a premium to live in transit oriented development.

For my own personal analysis, I want observe the relationship between bike lanes and various demograpic statistics in Sacramento California, where I live. similar to the analysis in the textbook. I don't think I'll confidently be able to infer any causation. But, I believe that I will find that areas with more bike lanes will have a higher percentage of working age young adults living nearby, and possibly an increasing number of working age young adults living nearby over time. I also plant to look at statistics like average rent, percent bachelors degree and more.

Some challenges I forsee are that my bike lane data is for the city of Sacramento while the census data is for the county. I am going to need to find a way to limit census data to the city as well. I think I may need to do this by getting a third layer that constitutes a city map and clipping my county data.

I think that one of the hardest things as well will be to accurately choose the variables I need from the census data

```{r}
library(tidyverse)
library(tidycensus)
library(sf)
library(kableExtra)

options(scipen=999)
options(tigris_class = "sf")
```

